### ISSUE TITLE
Recommend update() method

### ISSUE THREAD

**Issue by AZChris83** [QuentinCG/Arduino-I2C-EEPROM-library#3]
Just like the Arduino standard method, recommend a update() method so that an unchanged value doesn't get written causing wear.

Process:
Read the value from the address passed
If the value is different, write it, otherwise skip.

**Comment by QuentinCG** [comment]
Sure, this seems quite fast to do (I'll do it in the repo when I'll have some time to do the test).

If you have time to do the test (and a pull request), the function should be something like this (not tested as I don't have compiler & arduino with me right now so please can you verify if it works ?):

- I2CEEPROM.h (after `write()` and `read()`)

```cpp
    /*!
     * \brief update Update one byte \p data in EEPROM device at EEPROM internal address \p address if not already the correct one (will read then write if not identical)
     * \param address (unsigned int) EEPROM internal address (most of the time, first address is 0x00)
     * \param data (byte) Byte to write at EEPROM internal address \p address
     */
    void update(unsigned int address, byte data) const;
```

 - I2CEEPROM.cpp (after `write()` and `read()`):
```cpp
void I2CEEPROM::update(unsigned int address, byte data) const
{
  if (read(address) != data)
  {
    write(address, data);
  }
  else
  {
    // Data to write is the same as data already written
    // => No need to write !
  }
}
```

- README.md:  Add explanation on this new feature
- Example: Fill ino files with this function (commented next to 'write' for example)
- All files: Upgrade version of the lib

**Comment by QuentinCG** [comment]
I added the method.
The library is now in version 1.3.

Release package is available here: https://github.com/QuentinCG/Arduino-I2C-EEPROM-library/releases

**Comment by AZChris83** [comment]
Will test when I have some chips on hand. Thanks for taking the suggestion!
